currencies = {
    "AED": { "name": "United Arab Emirates dirham", "region": 2, "shortlist": 0},
    "AFN": { "name": "Afghan afghanis", "region": 3, "shortlist": 0},
    "ALL": { "name": "Albanian lek", "region": 1, "shortlist": 0},
    "AMD": { "name": "Armenian dram", "region": 2, "shortlist": 0},
    "ANG": { "name": "Netherlands Antillean guilder", "region": 6, "shortlist": 0},
    "AOA": { "name": "Angolan kwanza", "region": 10, "shortlist": 0},
    "ARS": { "name": "Argentine peso", "region": 7, "shortlist": 1},
    "AUD": { "name": "Australian dollar", "region": 8, "shortlist": 1},
    "AWG": { "name": "Aruban florin", "region": 6, "shortlist": 0},
    "AZN": { "name": "Azerbaijani manat", "region": 2, "shortlist": 0},
    "BAM": { "name": "Bosnia and Herzegovina convertible mark", "region": 1, "shortlist": 0},
    "BBD": { "name": "Barbados dollar", "region": 6, "shortlist": 0},
    "BDT": { "name": "Bangladeshi taka", "region": 4, "shortlist": 0},
    "BGN": { "name": "Bulgarian lev", "region": 1, "shortlist": 0},
    "BHD": { "name": "Bahraini dinar", "region": 2, "shortlist": 0},
    "BIF": { "name": "Burundian franc", "region": 11, "shortlist": 0},
    "BMD": { "name": "Bermudian dollar", "region": 6, "shortlist": 0},
    "BND": { "name": "Brunei dollar", "region": 4, "shortlist": 0},
    "BOB": { "name": "Boliviano", "region": 7, "shortlist": 0},
    "BRL": { "name": "Brazilian real", "region": 7, "shortlist": 1},
    "BSD": { "name": "Bahamian dollar", "region": 6, "shortlist": 0},
    "BTC": { "name": "Bitcoin", "region": 0, "shortlist": 0},
    "BTN": { "name": "Bhutanese ngultrum", "region": 4, "shortlist": 0},
    "BWP": { "name": "Botswana pula", "region": 11, "shortlist": 0},
    "BYN": { "name": "Belarusian ruble", "region": 1, "shortlist": 0},
    "BZD": { "name": "Belize dollar", "region": 5, "shortlist": 0},
    "CAD": { "name": "Canadian dollar", "region": 5, "shortlist": 1},
    "CDF": { "name": "Congolese franc", "region": 10, "shortlist": 0},
    "CHF": { "name": "Swiss franc", "region": 1, "shortlist": 1},
    "CLF": { "name": "Unidad de Fomento", "region": 7, "shortlist": 0},
    "CLP": { "name": "Chilean peso", "region": 7, "shortlist": 0},
    "CNH": { "name": "Chinese yuan (Hong Kong)", "region": 3, "shortlist": 0},
    "CNY": { "name": "Renminbi (Chinese) yuan", "region": 3, "shortlist": 1},
    "COP": { "name": "Colombian peso", "region": 7, "shortlist": 0},
    "CRC": { "name": "Costa Rican colon", "region": 5, "shortlist": 0},
    "CUC": { "name": "Cuban convertible peso", "region": 6, "shortlist": 0},
    "CUP": { "name": "Cuban peso", "region": 6, "shortlist": 0},
    "CVE": { "name": "Cape Verdean escudo", "region": 10, "shortlist": 0},
    "CZK": { "name": "Czech koruna", "region": 1, "shortlist": 0},
    "DJF": { "name": "Djiboutian franc", "region": 11, "shortlist": 0},
    "DKK": { "name": "Danish krone", "region": 1, "shortlist": 0},
    "DOP": { "name": "Dominican peso", "region": 6, "shortlist": 0},
    "DZD": { "name": "Algerian dinar", "region": 9, "shortlist": 1},
    "EGP": { "name": "Egyptian pound", "region": 9, "shortlist": 1},
    "ERN": { "name": "Eritrean nakfa", "region": 11, "shortlist": 0},
    "ETB": { "name": "Ethiopian birr", "region": 11, "shortlist": 0},
    "EUR": { "name": "Euro", "region": 1, "shortlist": 1},
    "FJD": { "name": "Fiji dollar", "region": 8, "shortlist": 0},
    "FKP": { "name": "Falkland Islands pound", "region": 7, "shortlist": 0},
    "GBP": { "name": "Pound sterling", "region": 1, "shortlist": 1},
    "GEL": { "name": "Georgian lari", "region": 2, "shortlist": 0},
    "GGP": { "name": "Guernsey pound", "region": 1, "shortlist": 0},
    "GHS": { "name": "Ghanaian cedi", "region": 10, "shortlist": 0},
    "GIP": { "name": "Gibraltar pound", "region": 1, "shortlist": 0},
    "GMD": { "name": "Gambian dalasi", "region": 10, "shortlist": 0},
    "GNF": { "name": "Guinean franc", "region": 10, "shortlist": 0},
    "GTQ": { "name": "Guatemalan quetzal", "region": 5, "shortlist": 0},
    "GYD": { "name": "Guyanese dollar", "region": 7, "shortlist": 0},
    "HKD": { "name": "Hong Kong dollar", "region": 3, "shortlist": 0},
    "HNL": { "name": "Honduran lempira", "region": 5, "shortlist": 0},
    "HRK": { "name": "Croatian kuna", "region": 1, "shortlist": 0},
    "HTG": { "name": "Haitian gourde", "region": 6, "shortlist": 0},
    "HUF": { "name": "Hungarian forint", "region": 1, "shortlist": 0},
    "IDR": { "name": "Indonesian rupiah", "region": 4, "shortlist": 0},
    "ILS": { "name": "Israeli new shekel", "region": 2, "shortlist": 0},
    "IMP": { "name": "Isle of Man pound", "region": 1, "shortlist": 0},
    "INR": { "name": "Indian rupee", "region": 4, "shortlist": 1},
    "IQD": { "name": "Iraqi dinar", "region": 2, "shortlist": 0},
    "IRR": { "name": "Iranian rial", "region": 4, "shortlist": 0},
    "ISK": { "name": "Icelandic króna", "region": 1, "shortlist": 0},
    "JEP": { "name": "Jersey pound", "region": 1, "shortlist": 0},
    "JMD": { "name": "Jamaican dollar", "region": 6, "shortlist": 0},
    "JOD": { "name": "Jordanian dinar", "region": 2, "shortlist": 0},
    "JPY": { "name": "Japanese yen", "region": 3, "shortlist": 1},
    "KES": { "name": "Kenyan shilling", "region": 11, "shortlist": 0},
    "KGS": { "name": "Kyrgyzstani som", "region": 3, "shortlist": 0},
    "KHR": { "name": "Cambodian riel", "region": 4, "shortlist": 0},
    "KMF": { "name": "Comoro franc", "region": 11, "shortlist": 0},
    "KPW": { "name": "North Korean won", "region": 3, "shortlist": 0},
    "KRW": { "name": "South Korean won", "region": 3, "shortlist": 1},
    "KWD": { "name": "Kuwaiti dinar", "region": 2, "shortlist": 1},
    "KYD": { "name": "Cayman Islands dollar", "region": 6, "shortlist": 0},
    "KZT": { "name": "Kazakhstani tenge", "region": 3, "shortlist": 0},
    "LAK": { "name": "Lao kip", "region": 4, "shortlist": 0},
    "LBP": { "name": "Lebanese pound", "region": 2, "shortlist": 0},
    "LKR": { "name": "Sri Lankan rupee", "region": 4, "shortlist": 0},
    "LRD": { "name": "Liberian dollar", "region": 10, "shortlist": 0},
    "LSL": { "name": "Lesotho loti", "region": 11, "shortlist": 0},
    "LYD": { "name": "Libyan dinar", "region": 9, "shortlist": 0},
    "MAD": { "name": "Moroccan dirham", "region": 9, "shortlist": 0},
    "MDL": { "name": "Moldovan leu", "region": 1, "shortlist": 0},
    "MGA": { "name": "Malagasy ariary", "region": 11, "shortlist": 0},
    "MKD": { "name": "Macedonian denar", "region": 1, "shortlist": 0},
    "MMK": { "name": "Myanmar kyat", "region": 4, "shortlist": 0},
    "MNT": { "name": "Mongolian tögrög", "region": 3, "shortlist": 0},
    "MOP": { "name": "Macanese pataca", "region": 3, "shortlist": 0},
    "MRU": { "name": "Mauritanian ouguiya", "region": 2, "shortlist": 0},
    "MUR": { "name": "Mauritian rupee", "region": 11, "shortlist": 0},
    "MVR": { "name": "Maldivian rufiyaa", "region": 4, "shortlist": 0},
    "MWK": { "name": "Malawian kwacha", "region": 11, "shortlist": 0},
    "MXN": { "name": "Mexican peso", "region": 5, "shortlist": 0},
    "MYR": { "name": "Malaysian ringgit", "region": 4, "shortlist": 0},
    "MZN": { "name": "Mozambican metical", "region": 11, "shortlist": 0},
    "NAD": { "name": "Namibian dollar", "region": 11, "shortlist": 0},
    "NGN": { "name": "Nigerian naira", "region": 10, "shortlist": 0},
    "NIO": { "name": "Nicaraguan córdoba", "region": 5, "shortlist": 0},
    "NOK": { "name": "Norwegian krone", "region": 1, "shortlist": 1},
    "NPR": { "name": "Nepalese rupee", "region": 4, "shortlist": 0},
    "NZD": { "name": "New Zealand dollar", "region": 8, "shortlist": 1},
    "OMR": { "name": "Omani rial", "region": 2, "shortlist": 0},
    "PAB": { "name": "Panamanian balboa", "region": 5, "shortlist": 0},
    "PEN": { "name": "Peruvian sol", "region": 7, "shortlist": 0},
    "PGK": { "name": "Papua New Guinean kina", "region": 8, "shortlist": 0},
    "PHP": { "name": "Philippine peso", "region": 4, "shortlist": 0},
    "PKR": { "name": "Pakistani rupee", "region": 4, "shortlist": 0},
    "PLN": { "name": "Polish złoty", "region": 1, "shortlist": 0},
    "PYG": { "name": "Paraguayan guaraní", "region": 7, "shortlist": 0},
    "QAR": { "name": "Qatari riyal", "region": 2, "shortlist": 0},
    "RON": { "name": "Romanian leu", "region": 1, "shortlist": 0},
    "RSD": { "name": "Serbian dinar", "region": 1, "shortlist": 0},
    "RUB": { "name": "Russian ruble", "region": 1, "shortlist": 1},
    "RWF": { "name": "Rwandan franc", "region": 11, "shortlist": 0},
    "SAR": { "name": "Saudi riyal", "region": 2, "shortlist": 1},
    "SBD": { "name": "Solomon Islands dollar", "region": 8, "shortlist": 0},
    "SCR": { "name": "Seychelles rupee", "region": 11, "shortlist": 0},
    "SDG": { "name": "Sudanese pound", "region": 9, "shortlist": 0},
    "SEK": { "name": "Swedish krona", "region": 1, "shortlist": 1},
    "SGD": { "name": "Singapore dollar", "region": 4, "shortlist": 1},
    "SHP": { "name": "Saint Helena pound", "region": 10, "shortlist": 0},
    "SLL": { "name": "Sierra Leonean leone", "region": 10, "shortlist": 0},
    "SOS": { "name": "Somali shilling", "region": 11, "shortlist": 0},
    "SRD": { "name": "Surinamese dollar", "region": 7, "shortlist": 0},
    "SSP": { "name": "South Sudanese pound", "region": 11, "shortlist": 0},
    "STN": { "name": "São Tomé and Príncipe dobra", "region": 10, "shortlist": 0},
    "SVC": { "name": "Salvadoran colón", "region": 5, "shortlist": 0},
    "SYP": { "name": "Syrian pound", "region": 2, "shortlist": 0},
    "SZL": { "name": "Swazi lilangeni", "region": 11, "shortlist": 0},
    "THB": { "name": "Thai baht", "region": 4, "shortlist": 0},
    "TJS": { "name": "Tajikistani somoni", "region": 3, "shortlist": 0},
    "TMT": { "name": "Turkmenistan manat", "region": 3, "shortlist": 0},
    "TND": { "name": "Tunisian dinar", "region": 9, "shortlist": 0},
    "TOP": { "name": "Tongan paʻanga", "region": 8, "shortlist": 0},
    "TRY": { "name": "Turkish lira", "region": 2, "shortlist": 1},
    "TTD": { "name": "Trinidad and Tobago dollar", "region": 6, "shortlist": 0},
    "TWD": { "name": "New Taiwan dollar", "region": 3, "shortlist": 0},
    "TZS": { "name": "Tanzanian shilling", "region": 11, "shortlist": 0},
    "UAH": { "name": "Ukrainian hryvnia", "region": 1, "shortlist": 0},
    "UGX": { "name": "Ugandan shilling", "region": 11, "shortlist": 0},
    "USD": { "name": "United States dollar", "region": 5, "shortlist": 1},
    "UYU": { "name": "Uruguayan peso", "region": 7, "shortlist": 0},
    "UZS": { "name": "Uzbekistan som", "region": 3, "shortlist": 0},
    "VES": { "name": "Venezuelan bolívar soberano", "region": 7, "shortlist": 0},
    "VND": { "name": "Vietnamese đồng", "region": 4, "shortlist": 0},
    "VUV": { "name": "Vanuatu vatu", "region": 8, "shortlist": 0},
    "WST": { "name": "Samoan tala", "region": 8, "shortlist": 0},
    "XAF": { "name": "CFA franc BEAC", "region": 10, "shortlist": 0},
    "XAG": { "name": "Silver", "region": 0, "shortlist": 0},
    "XAU": { "name": "Gold", "region": 0, "shortlist": 0},
    "XCD": { "name": "East Caribbean dollar", "region": 6, "shortlist": 0},
    "XDR": { "name": "Special drawing rights", "region": 0, "shortlist": 0},
    "XOF": { "name": "CFA franc BCEAO", "region": 10, "shortlist": 0},
    "XPD": { "name": "Palladium (one troy ounce)", "region": 0, "shortlist": 0},
    "XPF": { "name": "CFP franc (franc Pacifique)", "region": 0, "shortlist": 0},
    "XPT": { "name": "Platinum (one troy ounce)", "region": 0, "shortlist": 0},
    "YER": { "name": "Yemeni rial", "region": 2, "shortlist": 0},
    "ZAR": { "name": "South African rand", "region": 11, "shortlist": 1},
    "ZMW": { "name": "Zambian kwacha", "region": 11, "shortlist": 0},
    "ZWL": { "name": "Zimbabwean dollar", "region": 11, "shortlist": 0}
}
